# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Plex MCP Server with SSE support
FROM node:lts-alpine AS base
WORKDIR /app

# Install system dependencies and npm packages
RUN apk add --no-cache wget
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy source
COPY . .

# Create non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# Environment variables
ENV PLEX_VERIFY_SSL=true
ENV MCP_TRANSPORT=sse
ENV PORT=3000

# Expose the SSE port
EXPOSE 3000

# Health check for SSE mode
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1

# Start the MCP server
USER nextjs
CMD ["node", "index.js"]
