# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Auto-generated Dockerfile for Plex MCP Server
FROM node:lts-alpine AS base
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy source
COPY . .

# Default verify SSL
ENV PLEX_VERIFY_SSL=true

# Start the MCP server
CMD ["node", "index.js"]
